[workspace]
resolver = "2"
members = [
    "firmware",
    "led-effects",
    "led-effects-macros",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
libm = "0.2.15"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = 2
