[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F429ZI"
# rustflags = ["-C", "remark=all"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
